#!/bin/bash

RESULT_DIR=${HOME}/workspace/ici-workspace/ici/workloads/db/results

P_ACTIVE_XCD=2

# Five configs that fully saturate QPS

P_TARGET_CC=0 && P_WORKERS=1 && P_ARRIVAL_QPS=100000
HIP_VISIBLE_DEVICES=0 ./bin/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS} 2>&1 | tee ${RESULT_DIR}/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS}.out &

P_TARGET_CC=0 && P_WORKERS=2 && P_ARRIVAL_QPS=500000
HIP_VISIBLE_DEVICES=1 ./bin/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS} 2>&1 | tee ${RESULT_DIR}/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS}.out &

P_TARGET_CC=0 && P_WORKERS=4 && P_ARRIVAL_QPS=1000000
HIP_VISIBLE_DEVICES=2 ./bin/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS} 2>&1 | tee ${RESULT_DIR}/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS}.out &

P_TARGET_CC=0 && P_WORKERS=8 && P_ARRIVAL_QPS=1500000
HIP_VISIBLE_DEVICES=3 ./bin/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS} 2>&1 | tee ${RESULT_DIR}/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS}.out &

P_TARGET_CC=0 && P_WORKERS=16 && P_ARRIVAL_QPS=1800000
HIP_VISIBLE_DEVICES=4 ./bin/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS} 2>&1 | tee ${RESULT_DIR}/db-a_${P_ACTIVE_XCD}_${P_TARGET_CC}_${P_WORKERS}_${P_ARRIVAL_QPS}.out &
